### ISSUE TITLE
Inappropriate logic clear

### ISSUE THREAD

**Issue by ZipCPU** [wallento/wb2axi#1]
On a response from AXI, the request valid line is used to clear the respective *done lines.  This only works if the wishbone interface immediately drops the request.  If the interface is deeper in an interconnect, it may take several clocks for the cycle and strobe lines to be dropped.  In that case, multiple AXI requests will be issued given only one WB request.

The solution would be to not clear the *done flags until the WB cycle line is dropped, something that needs to happen in WB classic anyway before the next transmission.

Dan

**Comment by wallento** [comment]
Hi Dan, sorry, I entirely missed this one. Due to the bus cycle it is not allowed that the strobe and cycle are still there after a request unless it is a new one. In the registered feedback bus cycle, the transfer ends with (ack|err|rty)&cyc&stb. stb and cyc can both stay asserted and no wait state is needed for the next transfer. cyc&stb then is a new transfer. Do you agree?

**Comment by ZipCPU** [comment]
Thanks for responding!  No, I'm not sure I agree (yet), but I'm certainly far from certain.

So far, I don't see what you are describing anywhere in the WB spec.

The closest thing I see is the single read cycle in Fig 3-3, or equivalently the single write cycle in Fig 3-4.  In both of those cycles, however, the master drops STB andd CYC as soon as it sees ACK_I.

At issue, in my mind, is ... what happens if the ACK takes a couple of clocks before it can be returned?  All of the circuity in the middle will wait for the ACK.  Unless they also tear down the read/write cycle as well ... the slave needs to hold ACK_O, ERR_O, RTY_O, and DAT_O constant until the cycle gets torn down.

There are block read/write cycles too, but these also drop STB  between transactions--still not quite what you are describing.

Is there a picture describing a waveform where ACK is only one clock long and CYC&STB stay high into the next clock period?

**Comment by ZipCPU** [comment]
Just in case there's any confusion, I'm talking about the last step in the enclosed trace.

![wavedrom](https://user-images.githubusercontent.com/22348544/58363410-aec41100-7e71-11e9-8b91-1575f848a235.png)

... and part of the question is how to deal with a bus master that may be more than one clock removed from this one.

**Comment by wallento** [comment]
I think this is plainly not allowed in WB. The ACK cannot be registered unless the master is capable of completing the next transaction too.

Here is the registered feedback bus cycle, that we are talking about:
https://wishbone-interconnect.readthedocs.io/en/latest/04_registered.html

Rule 4.15 says that the cycle ends when the termination and stb are asserted. If you keep stb assigned after that, this is a new cycle. Also see Figure 25 and 26 about that. So, in your Figure above: In cycle 4 the first transfer terminates and in cycle 5 a new transfer starts.

**Comment by ZipCPU** [comment]
Ok, I think that's explaining a lot to me.

To expand my vision out one hierarchy level, I'm envisioning something similar to the trace below.

![wavedrom](https://user-images.githubusercontent.com/22348544/58425703-7fc3c000-8068-11e9-8ad5-8c6b252c0c86.png)

In this trace, a source creates the wishbone signals.  However, there's a clock lost in the interconnect between the source and the slave.  The slave then responds as you'd expect, and when the source sees the interconnect's response, it moves the slave on to the next transaction.  This could/would be worse if there's another clock lost on the return acknowledgment signal.

If I understand what you are saying, and after studying the [wishbone registered feedback page](https://wishbone-interconnect.readthedocs.io/en/latest/04_registered.html), this will never happen because the interconnect is *required* to be combinatorial.  Correct?

Dan

**Comment by ZipCPU** [comment]
I think I understand it now.

Thanks!

Dan
