### ISSUE TITLE
Wrong AxSIZE

### ISSUE THREAD

**Issue by ZipCPU** [wallento/wb2axi#2]
The core defines the AXI AWSIZE and ARSIZE registers as the DATA_WIDTH >> 4.  For the given data width of 32 bits, this would be 2, the correct answer.  However, for a data width of 64, this would be 4--the wrong answer.  Similarly for a data width of 16 bits, the data width should be 1, not 0.

The correct AxSIZE value should be $clog2(DATA_WIDTH)-3.

**Comment by wallento** [comment]
Thanks for reporting! #4 is correct then, right?

**Comment by ZipCPU** [comment]
Yeah, that looks good.
